CREATE SCHEMA IF NOT EXISTS employeedb;

CREATE TABLE employeedb.employee (
        employee_id INT8 GENERATED BY DEFAULT AS IDENTITY,
        first_name VARCHAR(30) NOT NULL,
        last_name VARCHAR(30) NOT NULL,
        department_id int8 NOT NULL,
        job_title VARCHAR(255) NOT NULL,
        gender VARCHAR(255) NOT NULL,
        date_of_birth DATE NOT NULL,
        PRIMARY KEY (employee_id)
    );

INSERT INTO employeedb.employee (first_name, last_name, department_id, job_title, gender, date_of_birth)
    VALUES('Vasili', 'Kostopravov', 1, 'director', 'MALE', '1989-12-24');
